# theme = Cursor Dark
# theme = Catppuccin Macchiato
# theme = TokyoNight Storm
# theme = Nord
# theme = Bright Lights
theme = Dracula+
# theme = Xcode Dark

# font-family = Fira Code
# font-family = "JetBrainsMono Nerd Font"
font-family = "IosevkaTerm Nerd Font"
font-family = "UDEV Gothic"

font-style = Regular
font-size = 22
font-feature = +calt
font-feature = +liga

fullscreen = false

background-opacity = 0.92
background-blur-radius = 8

quick-terminal-position = "top"
quick-terminal-screen = "main"
quick-terminal-animation-duration = 0
quick-terminal-autohide = true
keybind = "global:cmd+shift+t=toggle_quick_terminal"

window-padding-x = 6
window-padding-y = 6
window-padding-balance = true

window-decoration = true
macos-titlebar-style = transparent
macos-window-shadow = true

cursor-style = block
cursor-style-blink = true

mouse-hide-while-typing = true

scrollback-limit = 100000
confirm-close-surface = false

# 見えづらいならこれ試す
# font-thicken = true

# Quick Terminal
# keybind = "global:cmd+`=toggle_quick_terminal"

# 改行入り貼り付け事故を防ぐ
clipboard-paste-protection = true

# 再起動してもウィンドウ/タブ/分割を復元（メイン端末向け）
window-save-state = always
